# the string name of the object we have detected for the left camera and right camera
int32 left_detection_id
int32 right_detection_id

# the heading we need to turn to face our detected object in radians for the left camera and right camera
float32 left_heading
float32 right_heading

# the distance to the detected object in metres for the left camera and right camera
float32 left_distance
float32 right_distance
